# Generated by Django 4.2.15 on 2024-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_country_city_siteuser_city_siteuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='user_avatar',
            field=models.ImageField(blank=True, default='images_avatar/default.png', null=True, upload_to='images_avatar/%Y/%m/%d'),
        ),
    ]
